# Generated by Django 5.2.17 on 2026-08-22 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModelCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(blank=True)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('key_last4', models.CharField(blank=True, max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
