# Generated by Django 5.2.17 on 2026-08-25

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def copy_existing_credentials(apps, schema_editor):
    credential_model = apps.get_model("accounts", "UserModelCredential")
    profile_model = apps.get_model("accounts", "UserModelProfile")
    for credential in credential_model.objects.all().iterator():
        if not any((credential.api_url, credential.model, credential.encrypted_api_key)):
            continue
        profile_model.objects.create(
            user_id=credential.user_id,
            name=(str(credential.model or "").strip() or "默认模型")[:80],
            api_url=credential.api_url,
            model=credential.model,
            encrypted_api_key=credential.encrypted_api_key,
            key_last4=credential.key_last4,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModelProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("api_url", models.URLField(blank=True)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("encrypted_api_key", models.TextField(blank=True)),
                ("key_last4", models.CharField(blank=True, max_length=4)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-is_active", "name", "id"]},
        ),
        migrations.RunPython(copy_existing_credentials, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="usermodelprofile",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("user"),
                name="unique_user_model_profile_name_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="usermodelprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user",),
                name="unique_active_model_profile_per_user",
            ),
        ),
    ]
