# Generated by Django 5.2.17 on 2026-08-21 04:32

import attendance.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('mode', models.CharField(choices=[('standard', '标准考勤'), ('flexible', '弹性工作'), ('exempt', '免考勤'), ('part_time', '兼职'), ('shift', '轮班')], default='standard', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('grace_minutes', models.PositiveIntegerField(default=0)),
                ('cross_day_cutoff_minutes', models.PositiveIntegerField(default=180, help_text='凌晨多少分钟内的单条打卡需要进入跨日疑似队列', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(720)])),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#64748B', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '系统管理员'), ('hr', 'HR'), ('supervisor', '部门主管'), ('viewer', '只读')], default='viewer', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('probation', '试用期'), ('regular', '已转正'), ('founder', '创始人'), ('part_time', '兼职'), ('left', '已离职')], default='regular', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('expected_days_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_holder', models.CharField(blank=True, max_length=80)),
                ('bank_province', models.CharField(blank=True, max_length=80)),
                ('bank_branch', models.CharField(blank=True, max_length=200)),
                ('bank_card_number', models.CharField(blank=True, max_length=80)),
                ('alipay_account', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='attendance.attendancepolicy')),
                ('tags', models.ManyToManyField(blank=True, related_name='employees', to='attendance.employeetag')),
            ],
            options={
                'ordering': ['department', 'employee_no'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to=attendance.models.import_upload_path)),
                ('file_sha256', models.CharField(max_length=64)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('default_expected_days', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('matched_rows', models.PositiveIntegerField(default=0)),
                ('unmatched_rows', models.PositiveIntegerField(default=0)),
                ('suspicion_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawPunchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField()),
                ('employee_no', models.CharField(blank=True, max_length=40)),
                ('source_name', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=120)),
                ('attendance_rule', models.CharField(blank=True, max_length=120)),
                ('work_date', models.DateField()),
                ('raw_value', models.TextField(blank=True)),
                ('punches', models.JSONField(blank=True, default=list)),
                ('has_punch', models.BooleanField(default=False)),
                ('effective_has_punch', models.BooleanField(default=False)),
                ('match_status', models.CharField(choices=[('employee_no', '工号匹配'), ('name', '姓名匹配'), ('alias', '别名匹配'), ('unmatched', '未匹配')], default='unmatched', max_length=20)),
                ('is_cross_day_suspicion', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_days', to='attendance.importbatch')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_days', to='attendance.employee')),
            ],
            options={
                'ordering': ['source_row', 'work_date'],
            },
        ),
        migrations.CreateModel(
            name='CrossDaySuspicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_date', models.DateField()),
                ('work_date', models.DateField()),
                ('punch_text', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('assign_previous', '归入前一天'), ('keep_current', '保留当天')], default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.employee')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicions', to='attendance.importbatch')),
                ('raw_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cross_day_review', to='attendance.rawpunchday')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('due_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rest_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('adjustment_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('adjustment_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('actual_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('absence_count', models.PositiveIntegerField(default=0)),
                ('missing_punch_count', models.PositiveIntegerField(default=0)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('normal', '正常'), ('review', '需要复核'), ('approved', '已确认')], default='review', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('rule_trace', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_results', to='attendance.employee')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='attendance.importbatch')),
            ],
            options={
                'ordering': ['employee__department', 'employee__employee_no'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'employee'), name='unique_batch_employee_result')],
            },
        ),
        migrations.AddConstraint(
            model_name='rawpunchday',
            constraint=models.UniqueConstraint(fields=('batch', 'source_row', 'work_date'), name='unique_source_row_work_date'),
        ),
    ]
