# Generated by Django 5.2.17 on 2026-08-22 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(max_length=255, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('current_title', models.CharField(blank=True, max_length=120)),
                ('current_city', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BossAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('browser_profile', models.SlugField(max_length=80, unique=True)),
                ('cdp_port', models.PositiveIntegerField(unique=True)),
                ('daily_contact_limit', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('offline', '离线'), ('ready', '可用'), ('running', '执行中'), ('paused', '已暂停'), ('risk', '风控')], default='offline', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_users', models.ManyToManyField(blank=True, related_name='boss_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('jd', models.TextField(blank=True)),
                ('headcount', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', '招聘中'), ('paused', '已暂停'), ('closed', '已关闭')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boss_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='recruitment.bossaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('stage', models.CharField(choices=[('new', '新候选人'), ('to_contact', '待联系'), ('greeted', '已打招呼'), ('communicating', '沟通中'), ('waiting_resume', '待简历'), ('resume_received', '已收简历'), ('to_screen', '待筛选'), ('to_interview', '待面试'), ('interviewing', '面试中'), ('to_offer', '待 Offer'), ('hired', '已录用'), ('rejected', '已淘汰'), ('talent_pool', '人才库')], default='new', max_length=30)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.candidate')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.recruitmentjob')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recruitmentjob',
            constraint=models.UniqueConstraint(fields=('boss_account', 'external_id'), name='unique_boss_job'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job_application'),
        ),
    ]
