# Generated by Django 5.2.17 on 2026-08-22 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RpaWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], default='offline', max_length=16)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='bossaccount',
            name='browser_executable',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='bossaccount',
            name='browser_type',
            field=models.CharField(choices=[('chrome', 'Chrome'), ('edge', 'Edge')], default='chrome', max_length=16),
        ),
        migrations.AddField(
            model_name='bossaccount',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bossaccount',
            name='login_status',
            field=models.CharField(choices=[('unknown', '未检查'), ('browser_stopped', '浏览器未启动'), ('waiting_login', '等待登录'), ('waiting_human', '等待人工验证'), ('ready', '已登录'), ('error', '异常')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='bossaccount',
            name='user_data_dir',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='bossaccount',
            name='verification_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='RecruitmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_audits', to=settings.AUTH_USER_MODEL)),
                ('boss_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='recruitment.bossaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RpaTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('check_status', '检查状态'), ('sync_positions', '同步职位')], max_length=32)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('leased', '已领取'), ('running', '执行中'), ('waiting_human', '等待人工处理'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=24)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boss_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_tasks', to='recruitment.bossaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rpa_tasks', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='recruitment.rpaworker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RpaTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=16)),
                ('event', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recruitment.rpatask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='rpatask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'leased', 'running'])), fields=('boss_account',), name='unique_active_rpa_task_per_account'),
        ),
    ]
