# Generated by Django 5.2.17 on 2026-08-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_rpaworker_bossaccount_browser_executable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='recruitmentjob',
            name='boss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='recruitment.bossaccount'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='recruitment/resumes/%Y/%m')),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('source', models.CharField(choices=[('boss', 'BOSS 直聘'), ('upload', '人工上传'), ('demo', '演示数据')], default='boss', max_length=20)),
                ('processing_status', models.CharField(choices=[('pending', '待处理'), ('ready', '待 AI 评估'), ('error', '文件不可用')], default='ready', max_length=20)),
                ('is_demo', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='recruitment.jobapplication')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
