# Generated by Django 5.2.17 on 2026-08-24 02:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_recruitment_demo_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bossaccount',
            name='daily_message_limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='bossaccount',
            name='daily_resume_view_limit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='bossaccount',
            name='daily_search_limit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='AutomationApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('sync_positions', '同步职位'), ('greet', '打招呼'), ('request_resume', '索要简历'), ('view_online_resume', '查看在线简历'), ('send_interview', '发送面试邀约'), ('deep_match', '深度匹配')], max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('item_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', '待确认'), ('approved', '已确认'), ('rejected', '已拒绝'), ('expired', '已过期')], default='draft', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_automation_approvals', to=settings.AUTH_USER_MODEL)),
                ('boss_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_approvals', to='recruitment.bossaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_automation_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('waiting_human', '等待人工'), ('partial', '部分完成'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=24)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('total_items', models.PositiveIntegerField(default=1)),
                ('succeeded_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='recruitment.automationapproval')),
                ('boss_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_batches', to='recruitment.bossaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_execution_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_key', models.CharField(max_length=160)),
                ('target_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('leased', '已领取'), ('running', '执行中'), ('verifying', '核验中'), ('waiting_human', '等待人工'), ('succeeded', '成功'), ('failed', '失败'), ('skipped', '已跳过'), ('cancelled', '已取消')], default='pending', max_length=24)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recruitment.executionbatch')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, upload_to='recruitment/evidence/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='recruitment.stepexecution')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stepexecution',
            constraint=models.UniqueConstraint(fields=('batch', 'target_key'), name='unique_batch_target'),
        ),
    ]
