# Generated by Django 5.2.17 on 2026-08-24 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_automation_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('metric', models.CharField(choices=[('search', '候选人搜索'), ('deep_match', '深度匹配'), ('resume_view', '在线简历查看'), ('contact', '打招呼'), ('message', '发送消息')], max_length=24)),
                ('used', models.PositiveIntegerField(default=0)),
                ('boss_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_usage', to='recruitment.bossaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('boss_account', 'day', 'metric'), name='unique_daily_automation_usage')],
            },
        ),
    ]
