# Generated by Django 5.2.17 on 2026-08-24 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_automation_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpatask',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rpa_tasks', to='recruitment.automationapproval'),
        ),
        migrations.AddField(
            model_name='rpatask',
            name='execution_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rpa_tasks', to='recruitment.executionbatch'),
        ),
        migrations.AddField(
            model_name='rpatask',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rpatask',
            name='action',
            field=models.CharField(choices=[('check_status', '检查状态'), ('sync_positions', '同步职位'), ('greet', '打招呼'), ('request_resume', '索要简历'), ('view_online_resume', '查看在线简历'), ('send_interview', '发送面试邀约'), ('deep_match', '深度匹配')], max_length=32),
        ),
    ]
