# Generated by Django 5.2.17 on 2026-08-24 03:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_rpa_task_safety'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDiscovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('recommend', '推荐候选人'), ('search', '常规搜索'), ('deep_search', '深度搜索')], max_length=24)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('identity_quality', models.CharField(choices=[('platform', '平台标识'), ('fingerprint', '组合指纹')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('current_title', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('experience', models.CharField(blank=True, max_length=160)),
                ('education', models.CharField(blank=True, max_length=160)),
                ('advantage', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('contact_hint', models.CharField(blank=True, max_length=40)),
                ('expires_at', models.DateTimeField()),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boss_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_discoveries', to='recruitment.bossaccount')),
                ('imported_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_sources', to='recruitment.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_discoveries', to='recruitment.recruitmentjob')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('boss_account', 'job', 'fingerprint'), name='unique_account_job_discovery_fingerprint')],
            },
        ),
        migrations.CreateModel(
            name='CandidateExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('identity_quality', models.CharField(choices=[('platform', '平台标识'), ('fingerprint', '组合指纹')], max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('boss_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_identities', to='recruitment.bossaccount')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='recruitment.candidate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('boss_account', 'fingerprint'), name='unique_account_candidate_fingerprint')],
            },
        ),
    ]
