# Generated by Django 5.2.17 on 2026-08-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_candidatediscovery_candidateexternalidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpatask',
            name='action',
            field=models.CharField(choices=[('check_status', '检查状态'), ('sync_positions', '同步职位'), ('recommend_candidates', '推荐候选人'), ('search_candidates', '搜索候选人'), ('greet', '打招呼'), ('request_resume', '索要简历'), ('view_online_resume', '查看在线简历'), ('send_interview', '发送面试邀约'), ('deep_match', '深度匹配')], max_length=32),
        ),
    ]
