# Generated by Django 5.2.17 on 2026-08-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_alter_rpatask_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationapproval',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
