# Generated by Django 5.2.17 on 2026-08-24 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_automationapproval_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('new', '新候选人'), ('to_contact', '待联系'), ('greeted', '已打招呼'), ('communicating', '沟通中'), ('waiting_resume', '待简历'), ('resume_received', '已收简历'), ('to_screen', '待筛选'), ('to_interview', '待面试'), ('interviewing', '面试中'), ('to_offer', '待 Offer'), ('hired', '已录用'), ('rejected', '已淘汰'), ('talent_pool', '人才库')], max_length=30)),
                ('to_stage', models.CharField(choices=[('new', '新候选人'), ('to_contact', '待联系'), ('greeted', '已打招呼'), ('communicating', '沟通中'), ('waiting_resume', '待简历'), ('resume_received', '已收简历'), ('to_screen', '待筛选'), ('to_interview', '待面试'), ('interviewing', '面试中'), ('to_offer', '待 Offer'), ('hired', '已录用'), ('rejected', '已淘汰'), ('talent_pool', '人才库')], max_length=30)),
                ('source', models.CharField(choices=[('automation', '自动化'), ('manual', '人工调整')], max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('greet', '打招呼'), ('request_resume', '索要简历'), ('send_interview', '发送面试邀约')], max_length=32)),
                ('status', models.CharField(choices=[('draft', '待确认'), ('approved', '已确认'), ('pending', '待执行'), ('running', '执行中'), ('waiting_human', '等待人工'), ('succeeded', '成功'), ('failed', '失败'), ('skipped', '已跳过'), ('cancelled', '已取消')], default='draft', max_length=24)),
                ('message_snapshot', models.TextField()),
                ('target_snapshot', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor', models.CharField(blank=True, max_length=300)),
                ('last_message_preview', models.CharField(blank=True, max_length=500)),
                ('has_candidate_reply', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('online', '线上面试'), ('offline', '线下面试')], max_length=16)),
                ('location', models.CharField(max_length=500)),
                ('contact_name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(max_length=80)),
                ('node_type', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('position', models.JSONField(default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('enabled', '已启用'), ('disabled', '已停用')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='acquired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='external_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='resume',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resume',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('sha256', ''), _negated=True), fields=('candidate', 'sha256'), name='unique_candidate_resume_hash'),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(fields=('candidate', 'version'), name='unique_candidate_resume_version'),
        ),
        migrations.AddField(
            model_name='applicationstagehistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstagehistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='recruitment.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationstagehistory',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to='recruitment.rpatask'),
        ),
        migrations.AddField(
            model_name='conversationaction',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_actions', to='recruitment.jobapplication'),
        ),
        migrations.AddField(
            model_name='conversationaction',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_actions', to='recruitment.automationapproval'),
        ),
        migrations.AddField(
            model_name='conversationaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_actions', to='recruitment.executionbatch'),
        ),
        migrations.AddField(
            model_name='conversationaction',
            name='boss_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_actions', to='recruitment.bossaccount'),
        ),
        migrations.AddField(
            model_name='conversationaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_conversation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationaction',
            name='step',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_action', to='recruitment.stepexecution'),
        ),
        migrations.AddField(
            model_name='conversationsyncstate',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_state', to='recruitment.jobapplication'),
        ),
        migrations.AddField(
            model_name='conversationsyncstate',
            name='boss_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_states', to='recruitment.bossaccount'),
        ),
        migrations.AddField(
            model_name='interviewinvitation',
            name='action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_invitation', to='recruitment.conversationaction'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='recruitment.workflownode'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='recruitment.workflownode'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='boss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_versions', to='recruitment.bossaccount'),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='recruitment.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_templates', to='recruitment.workflowversion'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='recruitment.workflowversion'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='recruitment.workflowversion'),
        ),
        migrations.AddConstraint(
            model_name='workflowversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='unique_workflow_version'),
        ),
        migrations.AddConstraint(
            model_name='workflownode',
            constraint=models.UniqueConstraint(fields=('version', 'node_key'), name='unique_workflow_node_key'),
        ),
        migrations.AddConstraint(
            model_name='workflowedge',
            constraint=models.UniqueConstraint(fields=('version', 'source', 'target'), name='unique_workflow_edge'),
        ),
    ]
