# Generated by Django 5.2.17 on 2026-08-24 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_recruitment_archiving'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowedge',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('dry_run', '试运行'), ('formal', '正式运行')], default='dry_run', max_length=16)),
                ('status', models.CharField(choices=[('queued', '已排队'), ('running', '运行中'), ('waiting_human', '等待人工'), ('paused', '已暂停'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='queued', max_length=24)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('graph_snapshot', models.JSONField(default=dict)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_runs', to=settings.AUTH_USER_MODEL)),
                ('boss_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_runs', to='recruitment.bossaccount')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_runs', to='recruitment.recruitmentjob')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='recruitment.workflowversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(max_length=80)),
                ('node_type', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('blocked', '等待前置'), ('ready', '就绪'), ('running', '运行中'), ('waiting_human', '等待人工'), ('succeeded', '成功'), ('failed', '失败'), ('skipped', '已跳过'), ('cancelled', '已取消')], db_index=True, default='blocked', max_length=24)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='recruitment.workflowrun')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=16)),
                ('event', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recruitment.workflownoderun')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recruitment.workflowrun')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflownoderun',
            constraint=models.UniqueConstraint(fields=('run', 'node_key'), name='unique_workflow_run_node_key'),
        ),
    ]
