# Generated by Django 5.2.17 on 2026-08-24 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_workflow_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionbatch',
            name='workflow_node_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_batch', to='recruitment.workflownoderun'),
        ),
        migrations.AddField(
            model_name='rpatask',
            name='workflow_node_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rpa_task', to='recruitment.workflownoderun'),
        ),
    ]
