# Generated by Django 5.2.17 on 2026-08-25 04:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_jobapplication_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('fingerprint', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('candidate', '候选人'), ('hr', 'HR'), ('system', '系统')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recruitment.conversationsyncstate')),
            ],
            options={
                'ordering': ['sent_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HumanAttention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_type', models.CharField(choices=[('observing_candidate', '候选人观望'), ('greeting_required', '待人工打招呼'), ('account_login', '账号需要登录'), ('risk_control', '验证码或风控'), ('identity_ambiguous', '候选人身份歧义'), ('resume_request_failed', '求简历失败'), ('archive_failed', '简历归档失败'), ('other', '其他')], max_length=40)),
                ('status', models.CharField(choices=[('open', '待处理'), ('resolved', '已处理'), ('archived', '已归档')], db_index=True, default='open', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=220, unique=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='human_attentions', to='recruitment.jobapplication')),
                ('boss_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='human_attentions', to='recruitment.bossaccount')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='human_attentions', to='recruitment.recruitmentjob')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_human_attentions', to=settings.AUTH_USER_MODEL)),
                ('workflow_node_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='human_attentions', to='recruitment.workflownoderun')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='human_attentions', to='recruitment.workflowrun')),
            ],
            options={
                'ordering': ['-priority', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobRequirementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('requirement', '岗位需求'), ('persona', '候选人画像'), ('other', '其他补充')], max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirement_documents', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_documents', to='recruitment.recruitmentjob')),
            ],
            options={
                'ordering': ['category', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobRequirementDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='recruitment/job-documents/%Y/%m')),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='recruitment.jobrequirementdocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirement_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.AddField(
            model_name='jobrequirementdocument',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_documents', to='recruitment.jobrequirementdocumentversion'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='recruitment/message-attachments/%Y/%m')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_attachments', to='recruitment.resume')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='recruitment.conversationmessage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MessageSyncPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('interval_minutes', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('last_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boss_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_sync_policy', to='recruitment.bossaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SearchCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('source', models.CharField(choices=[('recommend', '推荐'), ('search', '常规搜索'), ('deep_search', '深度搜索')], max_length=24)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('queued', '已排队'), ('running', '运行中'), ('paused', '已暂停'), ('succeeded', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=16)),
                ('target_resume_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_scan_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('scanned_count', models.PositiveIntegerField(default=0)),
                ('pulled_resume_count', models.PositiveIntegerField(default=0)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('stop_reason', models.CharField(blank=True, choices=[('', '未停止'), ('target_reached', '达到拉取数量'), ('scan_limit', '达到扫描上限'), ('quota', '查看额度不足'), ('paywall', '遇到付费墙'), ('risk_control', '验证码或风控'), ('account_offline', '账号离线'), ('user_stopped', '人工停止'), ('error', '执行异常')], default='', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boss_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_campaigns', to='recruitment.bossaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_campaigns', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_campaigns', to='recruitment.recruitmentjob')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_campaigns', to='recruitment.workflowrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversationmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('conversation_state', 'external_id'), name='unique_conversation_external_message'),
        ),
        migrations.AddConstraint(
            model_name='conversationmessage',
            constraint=models.UniqueConstraint(fields=('conversation_state', 'fingerprint'), name='unique_conversation_message_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='jobrequirementdocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='unique_job_document_version'),
        ),
        migrations.AddConstraint(
            model_name='jobrequirementdocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'sha256'), name='unique_job_document_hash'),
        ),
        migrations.AddConstraint(
            model_name='messageattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('message', 'external_id'), name='unique_message_external_attachment'),
        ),
        migrations.AddConstraint(
            model_name='messageattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('sha256', ''), _negated=True), fields=('message', 'sha256'), name='unique_message_attachment_hash'),
        ),
    ]
