# Generated by Django 5.2.17 on 2026-08-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_conversationmessage_humanattention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowedge',
            name='condition',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
