# Generated by Django 5.2.17 on 2026-08-25 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_alter_resume_source_alter_rpatask_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rpatask',
            name='unique_active_rpa_task_per_account',
        ),
        migrations.AddConstraint(
            model_name='rpatask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['leased', 'running'])), fields=('boss_account',), name='unique_active_rpa_task_per_account'),
        ),
    ]
