# Generated by Django 5.2.17 on 2026-08-25 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_remove_rpatask_unique_active_rpa_task_per_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpatask',
            name='workflow_node_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rpa_tasks', to='recruitment.workflownoderun'),
        ),
    ]
