# Generated by Django 5.2.17 on 2026-08-25 06:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_alter_rpatask_workflow_node_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTextExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('job_document', '岗位文档'), ('resume', '简历')], max_length=24)),
                ('source_id', models.PositiveBigIntegerField()),
                ('source_sha256', models.CharField(max_length=64)),
                ('method', models.CharField(choices=[('docx', 'DOCX'), ('doc_convert', 'DOC 转换'), ('pdf_text', 'PDF 文字'), ('pdf_ocr', 'PDF OCR'), ('image_ocr', '图片 OCR')], max_length=24)),
                ('plain_text', models.TextField(blank=True)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('ready', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('source_kind', 'source_id', 'source_sha256'), name='unique_file_text_extraction_source')],
            },
        ),
        migrations.CreateModel(
            name='JobStandardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已启用'), ('superseded', '历史版本')], db_index=True, default='draft', max_length=16)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('unresolved_questions', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(default='job-standard-v1', max_length=40)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_job_standards', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_versions', to='recruitment.recruitmentjob')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_job_standards', to=settings.AUTH_USER_MODEL)),
                ('source_document_versions', models.ManyToManyField(blank=True, related_name='job_standard_versions', to='recruitment.jobrequirementdocumentversion')),
            ],
            options={
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AiProcessingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('job_standard', '岗位标准'), ('resume_structure', '简历结构化'), ('resume_score', '简历评分')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('waiting_config', '等待模型配置'), ('pending', '等待处理'), ('extracting', '文本提取中'), ('ocr', 'OCR 处理中'), ('model', '模型处理中'), ('waiting_review', '待人工确认'), ('succeeded', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=24)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('leased_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('result_ref', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_tasks', to='recruitment.jobrequirementdocumentversion')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_tasks', to='recruitment.recruitmentjob')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_processing_tasks', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_tasks', to='recruitment.resume')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_tasks', to='recruitment.jobstandardversion')),
            ],
            options={
                'ordering': ['available_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StructuredResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(default='resume-structure-v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structured_resumes', to='recruitment.filetextextraction')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structured_versions', to='recruitment.resume')),
            ],
            options={
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dimension_scores', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('verification_questions', models.JSONField(blank=True, default=list)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('recommendation', models.CharField(choices=[('advance', '建议进一步沟通'), ('review', '建议人工复核'), ('hold', '暂不建议推进')], max_length=32)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(default='resume-score-v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='recruitment.jobstandardversion')),
                ('structured_resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='recruitment.structuredresumeversion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobstandardversion',
            constraint=models.UniqueConstraint(fields=('job', 'version'), name='unique_job_standard_version'),
        ),
        migrations.AddConstraint(
            model_name='jobstandardversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('job',), name='unique_published_standard_per_job'),
        ),
        migrations.AddConstraint(
            model_name='structuredresumeversion',
            constraint=models.UniqueConstraint(fields=('resume', 'version'), name='unique_structured_resume_version'),
        ),
        migrations.AddConstraint(
            model_name='resumeassessment',
            constraint=models.UniqueConstraint(fields=('structured_resume', 'standard', 'version'), name='unique_resume_assessment_version'),
        ),
    ]
