# Generated by Django 5.2.17 on 2026-08-26 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0027_unique_active_check_status_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rpatask',
            name='unique_active_rpa_task_per_account',
        ),
        migrations.RemoveConstraint(
            model_name='rpatask',
            name='unique_active_check_status_per_account',
        ),
        migrations.AlterField(
            model_name='rpatask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('leased', '已领取'), ('running', '执行中'), ('cancel_requested', '正在取消'), ('waiting_human', '等待人工处理'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='rpatask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['leased', 'running', 'cancel_requested'])), fields=('boss_account',), name='unique_active_rpa_task_per_account'),
        ),
        migrations.AddConstraint(
            model_name='rpatask',
            constraint=models.UniqueConstraint(condition=models.Q(('action', 'check_status'), ('status__in', ['pending', 'leased', 'running', 'cancel_requested'])), fields=('boss_account', 'action'), name='unique_active_check_status_per_account'),
        ),
    ]
