# Generated by Django 5.2.17 on 2026-08-28 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0034_unlimited_local_resume_view_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprocessingtask',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_tasks', to='recruitment.resumeassessment'),
        ),
        migrations.AddField(
            model_name='resumeassessment',
            name='passed_score_line',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeassessment',
            name='passing_score_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='resumeassessment',
            name='scoring_policy_version',
            field=models.CharField(default='legacy-model-v1', max_length=40),
        ),
        migrations.AddField(
            model_name='resumeassessment',
            name='system_recommendation',
            field=models.CharField(blank=True, choices=[('advance', '建议进一步沟通'), ('review', '建议人工复核'), ('hold', '暂不建议推进')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='aiprocessingtask',
            name='kind',
            field=models.CharField(choices=[('job_standard', '岗位标准'), ('resume_structure', '简历结构化'), ('resume_score', '简历评分'), ('resume_report', '简历分析报告')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='ResumeAssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('succeeded', '已生成'), ('failed', '生成失败')], max_length=16)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(default='resume-report-v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='recruitment.resumeassessment')),
            ],
            options={
                'ordering': ['-version', '-id'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'version'), name='unique_resume_assessment_report_version')],
            },
        ),
    ]
